pipeline:

  deploy_to_notprod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - URL=tableau-wip.notprod.dq.homeoffice.gov.uk
    commands:
      - export KEYCLOAK_SECRET=$$NOTPROD_KEYCLOAK_SECRET
      - export KEYCLOAK_DISCOVERY_URL=$$NOTPROD_KEYCLOAK_DISCOVERY_URL
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - kd -f network-policy.yaml -f service.yaml -f ingress.yaml -f secret.yaml -f deployment.yaml
    secrets:
      - NOTPROD_KEYCLOAK_SECRET
      - NOTPROD_KEYCLOAK_DISCOVERY_URL
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: push

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps
      - INSECURE_SKIP_TLS_VERIFY=true
      - URL=tableau-wip.notprod.dq.homeoffice.gov.uk
    commands:
      - export KEYCLOAK_SECRET=$$PROD_KEYCLOAK_SECRET
      - export KEYCLOAK_DISCOVERY_URL=$$PROD_KEYCLOAK_DISCOVERY_URL
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - kd -f network-policy.yaml -f service.yaml -f ingress.yaml -f secret.yaml -f deployment.yaml
    secrets:
      - PROD_KEYCLOAK_SECRET
      - PROD_KEYCLOAK_DISCOVERY_URL
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER

    when:
      environment: production
      event: deployment
